spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: Venky@5248
    driver-class-name: com.mysql.cj.jdbc.Driver  # Specify the MySQL JDBC driver class (important for older versions of Spring Boot)
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect  # Specify MySQL dialect explicitly
    hibernate:
      ddl-auto: create


